/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import java.sql.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 * Course Selection Form - Second step of the exam committee proposal wizard.
 * Displays and allows selection of courses based on exam details.
 * 
 * @author ACER
 */
public class Course extends javax.swing.JFrame {

    /**
     * Creates new form Course
     */
    public Course() {
        initComponents();
    }
    public Course(String msg){
        initComponents();
        //jLabel2.setText(msg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Course Details");

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButton1.setText("Choose Subject");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Next_page");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jButton3)
                        .addGap(169, 169, 169)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(360, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(141, 141, 141))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Clear existing items
        jComboBox1.removeAllItems();
        jComboBox2.removeAllItems();
        
        Connection conn = null;
        PreparedStatement pstmt = null;
        ResultSet rs = null;
        
        try {
            conn = DatabaseConnection.getConnection();
            
            // Get exam details from exam_table
            String selectExamSql = "SELECT * FROM exam_table ORDER BY id DESC LIMIT 1";
            pstmt = conn.prepareStatement(selectExamSql);
            rs = pstmt.executeQuery();
            
            if (!rs.next()) {
                DatabaseConnection.showError(this, "Error", "No exam details found. Please go back and enter exam information.");
                return;
            }
            
            String level = rs.getString("level");
            String semester = rs.getString("semester");
            
            // Close previous result set and statement
            DatabaseConnection.closeResultSet(rs);
            DatabaseConnection.closePreparedStatement(pstmt);
            
            // Construct table name (note: dynamic table names require careful validation)
            String tableName = "l_" + level + "_s_" + semester;
            
            // Validate table name to prevent SQL injection
            if (!tableName.matches("^l_\\d+_s_[a-z]+$")) {
                DatabaseConnection.showError(this, "Error", "Invalid exam level or semester.");
                return;
            }
            
            // Note: For production, consider using a mapping table instead of dynamic table names
            // For now, using prepared statement with table name validation
            String selectCoursesSql = "SELECT * FROM " + tableName;
            
            pstmt = conn.prepareStatement(selectCoursesSql);
            rs = pstmt.executeQuery();
            
            boolean hasCourses = false;
            while (rs.next()) {
                hasCourses = true;
                String courseCode = rs.getString("course_code");
                String courseTitle = rs.getString("course_title");
                String examType = rs.getString("exam_type");
                String credit = rs.getString("credit");
                
                String courseDisplay = courseTitle + " " + examType + " " + credit + " (Credit)";
                
                if (courseCode != null && !courseCode.isEmpty()) {
                    jComboBox1.addItem(courseCode);
                    jComboBox2.addItem(courseDisplay);
                }
            }
            
            if (!hasCourses) {
                DatabaseConnection.showError(this, "No Courses", 
                        "No courses found for the selected exam details. Please check the database.");
            } else {
                DatabaseConnection.showSuccess(this, "Success", "Courses loaded successfully.");
            }
            
        } catch (ClassNotFoundException e) {
            DatabaseConnection.showError(this, "Database Error", 
                    "MySQL JDBC Driver not found. Please check your classpath.");
            e.printStackTrace();
        } catch (SQLException e) {
            DatabaseConnection.showError(this, "Database Error", 
                    "Error loading courses: " + e.getMessage());
            e.printStackTrace();
        } catch (Exception e) {
            DatabaseConnection.showError(this, "Error", 
                    "An unexpected error occurred: " + e.getMessage());
            e.printStackTrace();
        } finally {
            DatabaseConnection.closeResultSet(rs);
            DatabaseConnection.closePreparedStatement(pstmt);
            DatabaseConnection.closeConnection(conn);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (jComboBox2.getSelectedItem() == null) {
            DatabaseConnection.showError(this, "Validation Error", "Please select a course first.");
            return;
        }
        
        String selectedCourse = jComboBox2.getSelectedItem().toString();
        
        if (!DatabaseConnection.isValidString(selectedCourse)) {
            DatabaseConnection.showError(this, "Validation Error", "Invalid course selection.");
            return;
        }
        
        Connection conn = null;
        PreparedStatement pstmt = null;
        
        try {
            conn = DatabaseConnection.getConnection();
            
            // Use PreparedStatement to prevent SQL injection
            String sql = "INSERT INTO course_table (name) VALUES (?)";
            pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, selectedCourse);
            
            int rowsAffected = pstmt.executeUpdate();
            
            if (rowsAffected > 0) {
                DatabaseConnection.showSuccess(this, "Success", "Course selected successfully!");
                
                // Navigate to next form
                Exam_Committee examCommitteeForm = new Exam_Committee();
                examCommitteeForm.setVisible(true);
                this.dispose();
            } else {
                DatabaseConnection.showError(this, "Error", "Failed to save course selection.");
            }
            
        } catch (ClassNotFoundException e) {
            DatabaseConnection.showError(this, "Database Error", 
                    "MySQL JDBC Driver not found. Please check your classpath.");
            e.printStackTrace();
        } catch (SQLException e) {
            DatabaseConnection.showError(this, "Database Error", 
                    "Error saving course selection: " + e.getMessage());
            e.printStackTrace();
        } catch (Exception e) {
            DatabaseConnection.showError(this, "Error", 
                    "An unexpected error occurred: " + e.getMessage());
            e.printStackTrace();
        } finally {
            DatabaseConnection.closePreparedStatement(pstmt);
            DatabaseConnection.closeConnection(conn);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        exam pp = new exam();
        pp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Course().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
